# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Gaurav Chopra
# Description of the Site
description: I am a Web developer, a problem solver with a passion for WordPress.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Gaurav, Chopra, Gaurav Chopra, GRVC
# URL for the Image of custom Favicon
favicon-url: https://images.weserv.nl/?url=https://github.com/higrv.png&h=300&w=300&fit=cover&mask=circle&maxage=7d

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gauravchopra.biz@gmail.com
facebook_username: 
twitter_username: 
instagram_username: tejasvaar
linkedin_username: higrv
github_username:  higrv
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Gaurav Chopra
# URL for the Image of the Author
author-image: https://images.weserv.nl/?url=https://github.com/higrv.png&h=300&w=300&fit=cover&mask=circle&maxage=7d
# 60 Words About the Author
author-about: I am a Web developer, a problem solver with a passion for WordPress.<br>With over 2 years' experience in Web development, I've worked with 20+ SMEs across India and US to bring their ideas to life. I'm curious about the world around me and I love learning from my experiences. On a personal front I make music and play Table Tennis for fun.<br>At present, I am working as a freelance Web Developer.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/higrv

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
